" if v:lang =~ "utf8$" || v:lang =~ "UTF-8$"
   set fileencodings=utf-8,gb2312,gbk,latin1
   set termencoding=utf-8
   set encoding=utf-8
" endif
"
call plug#begin('~/.vim/plugged')
Plug 'dominikduda/vim_current_word'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'preservim/nerdtree'
Plug 'sheerun/vim-polyglot'
Plug 'pineapplegiant/spaceduck'
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/vim-lsp'
Plug 'prabirshrestha/asyncomplete-lsp.vim'
Plug 'mattn/vim-lsp-settings'
call plug#end()

hi CurrentWord ctermbg=53
hi CurrentWordTwins ctermbg=237 cterm=underline

"{{ set up colorscheme
if exists('+termguicolors')
   let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
   let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
   set termguicolors
endif
colorscheme spaceduck
"}} set up colorscheme

set listchars=tab:!·,trail:·

"{{{ LSP configurations
" Classic Vim LSP stack. vim-lsp supports Vim 8 and Neovim, and
" vim-lsp-settings handles server registration/installation.
let g:lsp_settings_servers_dir = expand('~/.vim-lsp-settings/servers')
let g:lsp_settings_root_markers = [
      \ '.git', '.git/', '.svn', '.hg',
      \ 'go.mod', 'pyproject.toml',
      \ 'setup.py', 'requirements.txt',
      \ 'compile_commands.json',
      \ 'compile_flags.txt'
      \ ]
let g:lsp_settings_filetype_c = ['clangd']
let g:lsp_settings_filetype_cpp = ['clangd']
let g:lsp_settings_filetype_go = ['gopls']
let g:lsp_settings_filetype_python = ['pylsp']
let g:lsp_preview_float = 1
let g:lsp_preview_autoclose = 1
let g:lsp_document_highlight_enabled = 1
let g:lsp_diagnostics_echo_cursor = 1
let g:lsp_format_sync_timeout = 1000
let g:lsp_semantic_enabled = 1
let g:lsp_semantic_delay = 500
let g:asyncomplete_auto_popup = 1
let g:asyncomplete_auto_completeopt = 0
set completeopt=menuone,noinsert,noselect

inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
inoremap <expr> <CR> pumvisible() ? asyncomplete#close_popup() : "\<CR>"
imap <C-Space> <Plug>(asyncomplete_force_refresh)
imap <C-@> <Plug>(asyncomplete_force_refresh)

function! s:asyncomplete_force_refresh_after(char) abort
  if &paste || !exists('g:asyncomplete_loaded')
    return a:char
  endif
  return a:char . (pumvisible() ? "\<C-e>" : '') . "\<C-r>=asyncomplete#_force_refresh()\<CR>"
endfunction

function! s:asyncomplete_force_refresh_after_if_prev(char, prev) abort
  if col('.') < 2 || getline('.')[col('.') - 2] !=# a:prev
    return a:char
  endif
  return s:asyncomplete_force_refresh_after(a:char)
endfunction

augroup premium_lsp_completion
  autocmd!
  autocmd FileType go inoremap <buffer><expr> . <SID>asyncomplete_force_refresh_after('.')
  autocmd FileType c,cpp inoremap <buffer><expr> . <SID>asyncomplete_force_refresh_after('.')
  autocmd FileType c,cpp inoremap <buffer><expr> > <SID>asyncomplete_force_refresh_after_if_prev('>', '-')
  autocmd FileType cpp inoremap <buffer><expr> : <SID>asyncomplete_force_refresh_after_if_prev(':', ':')
augroup END

function! s:on_lsp_buffer_enabled() abort
  setlocal omnifunc=lsp#complete
  if exists('+signcolumn')
    setlocal signcolumn=yes
  endif
  if exists('+tagfunc')
    setlocal tagfunc=lsp#tagfunc
  endif

  nmap <buffer> gd <plug>(lsp-definition)
  nmap <buffer> gr <plug>(lsp-references)
  nmap <buffer> gpr <plug>(lsp-references)
  nmap <buffer> gD <plug>(lsp-declaration)
  nmap <buffer> gi <plug>(lsp-implementation)
  nmap <buffer> gy <plug>(lsp-type-definition)
  nmap <buffer> K <plug>(lsp-hover)
  nmap <buffer> gpd <plug>(lsp-peek-definition)
  nmap <buffer> gpi <plug>(lsp-peek-implementation)
  nmap <buffer> gpy <plug>(lsp-peek-type-definition)
  nmap <buffer> gP <plug>(lsp-preview-close)
  nmap <buffer> <leader>rn <plug>(lsp-rename)
  nmap <buffer> <leader>ca <plug>(lsp-code-action)
  nmap <buffer> [g <plug>(lsp-previous-diagnostic)
  nmap <buffer> ]g <plug>(lsp-next-diagnostic)
  nnoremap <buffer> <leader>lf :LspDocumentFormat<CR>
endfunction

augroup premium_lsp
  autocmd!
  autocmd User lsp_buffer_enabled call s:on_lsp_buffer_enabled()
augroup END

function! s:goto_quickfix_file_window(is_loclist) abort
  if a:is_loclist
    let l:filewinid = get(getloclist(0, {'filewinid': 0}), 'filewinid', 0)
    if l:filewinid && win_gotoid(l:filewinid)
      return 1
    endif
  endif

  let l:prev_winid = win_getid(winnr('#'))
  if l:prev_winid && win_gotoid(l:prev_winid) && &buftype !=# 'quickfix'
    return 1
  endif

  for l:wininfo in getwininfo()
    if get(l:wininfo, 'tabnr', 0) == tabpagenr()
          \ && !get(l:wininfo, 'quickfix', 0)
          \ && getbufvar(l:wininfo.bufnr, '&buftype') ==# ''
      return win_gotoid(l:wininfo.winid)
    endif
  endfor

  return 0
endfunction

function! s:open_quickfix_item_in_vsplit(item) abort
  let l:lnum = max([get(a:item, 'lnum', 1), 1])
  let l:col = max([get(a:item, 'col', 1), 1])
  let l:bufnr = get(a:item, 'bufnr', 0)

  if l:bufnr > 0 && bufexists(l:bufnr)
    execute 'rightbelow vertical sbuffer ' . l:bufnr
  else
    let l:filename = get(a:item, 'filename', '')
    if empty(l:filename)
      echohl WarningMsg
      echom 'Quickfix item has no file to open'
      echohl None
      return
    endif
    execute 'rightbelow vertical split ' . fnameescape(l:filename)
  endif

  call cursor(l:lnum, l:col)
  normal! zvzz
endfunction

function! s:quickfix_open_vsplit() abort
  let l:qf_winid = win_getid()
  let l:wininfo = get(getwininfo(l:qf_winid), 0, {})
  if empty(l:wininfo) || !get(l:wininfo, 'quickfix', 0)
    return
  endif

  let l:is_loclist = get(l:wininfo, 'loclist', 0)
  let l:items = l:is_loclist ? getloclist(0) : getqflist()
  let l:idx = line('.')
  if l:idx < 1 || l:idx > len(l:items)
    echohl WarningMsg
    echom 'No quickfix item under cursor'
    echohl None
    return
  endif

  let l:item = l:items[l:idx - 1]
  if !get(l:item, 'valid', 1)
    echohl WarningMsg
    echom 'Quickfix item under cursor is not valid'
    echohl None
    return
  endif

  if !s:goto_quickfix_file_window(l:is_loclist)
    topleft new
  endif
  call s:open_quickfix_item_in_vsplit(l:item)
endfunction

augroup premium_quickfix
  autocmd!
  autocmd FileType qf nnoremap <buffer><silent> gv :<C-U>call <SID>quickfix_open_vsplit()<CR>
augroup END
"}}} LSP configurations

"{{{ vim-airline's status bar style
" powerline symbols
let g:airline_left_sep = ''
let g:airline_left_alt_sep = ''
let g:airline_right_sep = ''
let g:airline_right_alt_sep = ''
" }}}

" {{{ NERDTree configurations
nmap q :NERDTreeToggle<CR>
let g:NERDTreeShowLineNumbers=1
" }}} NERDTree configurations

set nocompatible	" Use Vim defaults (much better!)
set bs=indent,eol,start		" allow backspacing over everything in insert mode
"set ai			" always set autoindenting on
if has("vms")
  set nobackup          " do not keep a backup file, use versions instead
"else
"  set backup		" keep a backup file
endif
set viminfo='20,\"50	" read/write a .viminfo file, don't store more
			" than 50 lines of registers
set history=50		" keep 50 lines of command line history
set ruler		" show the cursor position all the time
set showcmd             " display incomplete commands
set showmode            " show mode
set incsearch           " do incremental searching

" Only do this part when compiled with support for autocommands
if has("autocmd")
  augroup redhat
  autocmd!
  " In text files, always limit the width of text to 78 characters
  " autocmd BufRead *.txt set tw=78
  " When editing a file, always jump to the last cursor position
  autocmd BufReadPost *
  \ if line("'\"") > 0 && line ("'\"") <= line("$") |
  \   exe "normal! g'\"" |
  \ endif
  " don't write swapfile on most commonly used directories for NFS mounts or USB sticks
  autocmd BufNewFile,BufReadPre /media/*,/run/media/*,/mnt/* set directory=~/tmp,/var/tmp,/tmp
  " start with spec file template
  autocmd BufNewFile *.spec 0r /usr/share/vim/vimfiles/template.spec
  augroup END
endif

if has("cscope") && filereadable("/usr/bin/cscope")
   set csprg=/usr/bin/cscope
   set csto=0
   set cst
   set nocsverb
   " add any database in current directory
   if filereadable("cscope.out")
      cs add $PWD/cscope.out
   " else add database pointed to by environment
   elseif $CSCOPE_DB != ""
      cs add $CSCOPE_DB
   endif
   set csverb
endif

" In many terminal emulators the mouse works just fine, thus enable it
if has('mouse')
  set mouse=a
endif

" Switch syntax highlighting on, when the terminal has colors
" Also switch on highlighting the last used search pattern.
if &t_Co > 2 || has("gui_running")
  syntax on
  set hlsearch
endif

filetype plugin on

set t_Co=256
if &term=="xterm"
     set t_Co=8
     set t_Sb=[4%dm
     set t_Sf=[3%dm
endif

" Don't wake up system with blinking cursor:
" http://www.linuxpowertop.org/known.php
let &guicursor = &guicursor . ",a:blinkon0"
set number
" {{{ 高亮当前行，行号，列
set cursorline
set cursorlineopt=both
autocmd ColorScheme * highlight CursorLineNr ctermfg=red guifg=orange
set cursorcolumn
" }}}
syntax enable
syntax on

" issues fixes {{{
" 解决 crontab -e 时，提示 contab: temp file must be edited in place
autocmd filetype contab setlocal nobackup nowritebackup
" }}} issue fixes

" fold and indent setting {{{
set autoindent
set tabstop=2
set softtabstop=2

set foldenable
set shiftwidth=1
" set foldmethod=syntax
set foldlevel=1
set foldclose=all
set foldopen=all
" }}} fold and indent setting
" ---------------------- cppfmt.vim -----------------------
" 输入设置
set backspace=2
set tabstop=2
set shiftwidth=2
set smarttab
set expandtab

" 缩进设置
set autoindent
set smartindent
set cindent
set cinoptions=g1,h1,i4,l1,m1,N-s,t0,W4,+2s,:2,(0

" 显示设置
" support gnu syntaxt
let c_gnu = 1

" show error for mixed tab-space
let c_space_errors = 1
"let c_no_tab_space_error = 1

" don't show gcc statement expression ({x, y;}) as error
let c_no_curly_error = 1

" 缩进格式修正：模板参数表，类初始化列表等
function! FixCppIndent()
    let l:cline_num = line('.')
    let l:cline = getline(l:cline_num)
    let l:pline_num = prevnonblank(l:cline_num - 1)
    let l:pline = getline(l:pline_num)
    while l:pline =~# '\(^\s*{\s*\|^\s*//\|^\s*/\*\|\*/\s*$\)'
        let l:pline_num = prevnonblank(l:pline_num - 1)
        let l:pline = getline(l:pline_num)
    endwhile
    let l:retv = cindent('.')
    let l:pindent = indent(l:pline_num)
    if l:pline =~# '^\s*template\s*<\s*$'
        let l:retv = l:pindent + &shiftwidth
    elseif l:pline =~# '^\s*template\s*<.*>\s*$'
        let l:retv = l:pindent
    elseif l:pline =~# '\s*typename\s*.*,\s*$'
        let l:retv = l:pindent
    elseif l:pline =~# '\s*typename\s*.*>\s*$'
        let l:retv = l:pindent - &shiftwidth
    elseif l:cline =~# '^\s*>\s*$'
        let l:retv = l:pindent - &shiftwidth
    elseif l:pline =~# '^\s\+: \S.*' " C++ initialize list
        let l:retv = l:pindent + 2
    elseif l:cline =~# '^\s*:\s*\w\+(' " C++ initialize list
        let l:retv = l:pindent + 4
    else
        echo "No match"
    endif
    return l:retv
endfunction
autocmd FileType cpp nested setlocal indentexpr=FixCppIndent()


" 保存时自动删除行尾多余的空白字符
function! RemoveTrailingSpace()
    if $VIM_HATE_SPACE_ERRORS != '0'
        normal m`
        silent! :%s/\s\+$//e
        normal ``
    endif
endfunction
autocmd BufWritePre * nested call RemoveTrailingSpace()

" 修复不一致的换行符，统一采用 Unix 换行符(\n)
function! FixInconsistFileFormat()
    if &fileformat == 'unix'
        silent! :%s/\r$//e
    endif
endfunction
autocmd BufWritePre * nested call FixInconsistFileFormat()

" 增加'CppLint'自定义命令，在冒号模式下输入:CppLint即可检查当前文件，也支持带文件名参数。
" 检查结果支持 vim 的  QuickFix 模式，在不离开 vim 的情况下跳转到出错行方便，修正。
function! CppLint(...)
    let l:args = join(a:000)
    if l:args == ""
        let l:args = expand("%")
        if l:args == ""
            let l:args = '*'
        endif
    endif
    let l:old_makeprg = &makeprg
    setlocal makeprg=cpplint.py
    execute "make " . l:args
    let &makeprg=old_makeprg
endfunction
command! -complete=file -nargs=* CppLint call CppLint('<args>')
" ---------------------- cppfmt.vim -----------------------
